### ISSUE TITLE
A new Vagrantfile

### ISSUE THREAD

**Issue by zhangcshcn** [DevOps2018-Promotions/promotions#14]
**As a** Developer
**I need** a `Vagrantfile`
**So that** members of the team can quickly get a development environment running

**Assumptions**:
- We will use `ubuntu/xeinal64`
- We will use `python 2.7` to develop
- We will have a `requirements.txt` file to list all the required python packages

**Acceptance Criteria**:
We should be able to start the environment with the required resources.

**Comment by Marcus9527** [comment]
Why not use Python 3.6+?

**Comment by zhangcshcn** [comment]
This's up to the Professor aka the BOSS.

**Comment by Marcus9527** [comment]
Did he mention that we have to use Python2.7? I guess I missed it.

**Comment by zhangcshcn** [comment]
In the very first lecture

**Comment by Marcus9527** [comment]
I see. Thanks.
