### ISSUE TITLE
Create a setup.cfg file

### ISSUE THREAD

**Issue by zhangcshcn** [DevOps2018-Promotions/promotions#25]
**As a** developer  
**I need** a setup.cfg file  
**So that** I only have to type `nosetests` to run the test suite.  

**Assumptions**:  
-  We use the python standard `unittest` package to write the test.  
-  All test files are located in ./test

**Acceptance Criteria**:  
`nosetests` successfully launch the test suite.

**Comment by bengunvl** [comment]
Copy what is in lab-vagrant\lab-flask-tdd\

[nosetests]
verbosity=2
with-spec=1
spec-color=1
with-coverage=1
cover-erase=1
cover-package=server,models
# with-xunit=1
# xunit-file=./reports/unittests.xml
# cover-xml=1
# cover-xml-file=./reports/coverage.xml

**Comment by bengunvl** [comment]
This has been set up correctly. If nothing else to add, I will close it.

**Comment by zhangcshcn** [comment]
This file is only for `nosetests`. I don't see any need for future amendments.   
Also, @bengunvl will you please add us to the co-owner of the organization so that we also have some degree of privilege to change the settings?

**Comment by bengunvl** [comment]
@zhangcshcn all members are admins now in the repo.

**Comment by bengunvl** [comment]
Completed OK and closed.
