### ISSUE TITLE
Types of promotions?

### ISSUE THREAD

**Issue by bengunvl** [DevOps2018-Promotions/promotions#3]
Decide on types of promotions (25%, buy one get one free, etc.)

**Comment by bengunvl** [comment]
Some promotions:

1. Price (20%) (25%) (50%) off $X or more of purchase
2. Price (20%) (25%) (50%) off under $X of purchase
3. Buy 1 get X free
4. Sign up for a Credit Card Rewards Visa Card and receive 70% one time off.
5. Shipping promotions. Free shipping above $100 of purchase
6. 12 hrs. flash sales on specific days
7. Cyber Monday 
8. Black Friday

**Comment by Marcus9527** [comment]
I think at our initial developing stage, we only need to cover the basic type.

**Comment by guangylegend** [comment]
I think we can cover 1,2 generally, and add date in our database to handle 6. 7 and 8 can be designed as a table of bundles. 4 can be achieved by adding user group column to database.

**Comment by bengunvl** [comment]
Yes, makes sense. So, we can focus on 1 or 2 promotions.
