### ISSUE TITLE
Modify the code to get database credentials from the ENV

### ISSUE THREAD

**Issue by bengunvl** [DevOps2018-Promotions/promotions#48]
**As a** developer 
**I need** to modify the database settings in the code base 
**So that** the program can get the database credentials from the env 

**Assumptions:** 
- We use MySQL service 
- The credentials will be provided from the VCAP_SERVICES environment variable in Bluemix 

**Acceptance Criteria:** 
The service interacts correctly with the database.

**Comment by zhangcshcn** [comment]
[This repo](https://github.com/nyu-devops/lab-flask-sqlalchemy) from the professor should be extremely helpful.
