### ISSUE TITLE
Add Swagger docs to document the API

### ISSUE THREAD

**Issue by zhangcshcn** [DevOps2018-Promotions/promotions#67]
**As a** developer
**I need** swagger docs
**So that** API can be documented

**Assumptions**:  
-  We will be using flasgger or Flask-RESTPlus to document API.

**Acceptance Criteria**: 
-  The documentation API must be at: /apidocs/index.html.
-  All the API should be correctly documented.

**Comment by zhangcshcn** [comment]
@bengunvl The flask app is initialized in `./app/__inti__.py`. I guess you also need to install the required python package for swagger, since we didn't include it in `./requirements.txt`
Also, please assign the issue to yourself and move it through the pipeline.

**Comment by bengunvl** [comment]
I cannot assign this to myself. Getting error. Can someone assign it to me?

**Comment by bengunvl** [comment]
I added Swagger configurations in and initialization in *./app/__inti__.py*.

Can check pipeline again?
